### ISSUE TITLE
covariance update for multi dimension capability

### ISSUE THREAD

**Issue by jjjjohnson** [ddbourgin/numpy-ml#16]
I think this line:
            outer = np.zeros((2, 2))
should change to 
           outer = np.zeros((self.d, self.d))

**Comment by jjjjohnson** [comment]
https://github.com/jjjjohnson/numpy-ml/blob/7889c4664c7bb7af2090a024dc9aa1ff70173e63/gmm/gmm.py#L124

**Comment by WuZhuoran** [comment]
I start a PR #22 on this. But after I change this line. The gmm model cannot pass the test. Could you please take a look? I copy the details in PR 22.

**Comment by WuZhuoran** [comment]
I update the test results in #22 again, it shows that the test is not stable. We can ask @ddbourgin for further discussion.
