### ISSUE TITLE
Possibly bug in decision tree

### ISSUE THREAD

**Issue by jcl2018** [ddbourgin/numpy-ml#39]
I was trying to run decision tree model using the very simple Iris dataset and I found a possible bug:

In trees/dt.py, line 160:
![image](https://user-images.githubusercontent.com/42528632/64308434-43590780-cf67-11e9-8c46-4aea55661882.png)

The problem is when the array "levels" only has one element, the threshold will be empty, and it will crush on line 164 when we call "gain.max()".

Please correct me if I'm wrong. Thank you for creating this useful repo!

**Comment by ddbourgin** [comment]
Hey @jcl2018 - thanks a lot for this report, and sorry for the slow response! You are, of course, absolutely right :). I'd be happy to accept a PR to fix this if you feel like writing one -- otherwise, I will try to fix this shortly. Thank you!
