### ISSUE TITLE
Error in LSTM Implementation

### ISSUE THREAD

**Issue by chaaland** [ddbourgin/numpy-ml#42]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
MacOS
- Python version:
3.7
- NumPy version:
1.17

**Describe the current behavior**
Forward pass implementation of LSTM is incorrect

**Describe the expected behavior**
Code is currently as below. This forget and update gate biases have typos
```python
        # compute the input to the gate functions at timestep t
        _Go = Zt @ Wo + bo
        _Gf = Zt @ Wf + bo
        _Gu = Zt @ Wu + bo
        _Gc = Zt @ Wc + bc
```

**Code to reproduce the issue**    

**Other info / logs**

**Comment by ddbourgin** [comment]
@chaaland - that's a bug, alright! Yet another reminder never to copy-paste code :) Thanks a ton for pointing this out :)
