### ISSUE TITLE
Installation not documented; couldn't find PyPi package or run tests

### ISSUE THREAD

**Issue by dmyersturnbull** [ddbourgin/numpy-ml#49]
This is an awesome library, thanks @ddbourgin!!

Users might not know the best way to install this package and try it out. (I didn't, so I eventually just copied the source files.)
Neither the readme nor readthedocs have install instructions.

I couldn't find it on PyPi or Anaconda, and there doesn't appear to be a `pyproject.toml`, `setup.cfg`, `setup.py`, or conda recipe.

Moreover, the tests aren't in a standard path like `tests/`.
This is uncommon and therefore confusion, and it makes it harder to run them.
*Edit: I wasn't expecting them under the source, so I initially wrote that I couldn't find them.*

I think it would be great to document how to install numpy-ml, and run its tests & see them to clarify the behavior of some of the functions.

There are some great build and CI tools for Python available, which I recently learned how to use effectively. I'm happy to make a pull request if it would be helpful.

**Comment by syncrostone** [comment]
I'm seconding this -- it would be great if numpy-ml were on PyPi or conda -- then I would feel comfortable including it in my package which I plan to put on PyPi.

**Comment by ddbourgin** [comment]
@dmyersturnbull and @syncrostone  - I think this is a great suggestion! I'm going to try to get this in shape for a pip package shortly, and will bump this once it's complete. Will then update docs for details on install etc.

**Comment by ddbourgin** [comment]
The package is (finally) [available on pypi](https://pypi.org/project/numpy-ml/0.1.0/)! Minimal installation documentation is available in the current [README](https://github.com/ddbourgin/numpy-ml/blob/master/README.md) and will be expanded in the coming days :)
