### ISSUE TITLE
Naive Bayes

### ISSUE THREAD

**Issue by sfsf9797** [ddbourgin/numpy-ml#67]
Hi, I am thinking about implementing Naive Bayes Methods and make a pull request. But I am unsure about the Unit testing part, Should I compare the performance with the ScikitLearn library?

**Comment by rishabh-jain14** [comment]
Issue solved. please refer to the pull request. #75

**Comment by rishabh-jain14** [comment]
Also, please let me know the places for improvement in the pull request. I am happy to work on the repository and learn in the best feasible way

**Comment by ddbourgin** [comment]
Closed via #68
